# 🧩 Project 3: Matrix Puzzle — Grid Operator

In [2]:
import numpy as np
grid = np.arange(1, 26).reshape(5,5)
print('Initial Grid:\n',grid)

Initial Grid:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


## Extract the center 3×3 block

In [3]:
block_3x3 = grid[1:4 , 1:4]
print(block_3x3)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


## Extract the center 2×2 block

In [4]:
block_2x2 = grid[1:3 , 1:3]
print(block_2x2)

[[ 7  8]
 [12 13]]


## Extract all corner elements only

In [11]:
corner = grid[[0,0,4,4],[0,4,0,4]] #[rows index] [column index]
print(corner)

[ 1  5 21 25]


## Extract both diagonals (main + anti-diagonal)

In [13]:
main_diagonal = grid[[0,1,2,3,4],[0,1,2,3,4]]
print(main_diagonal)

[ 1  7 13 19 25]


In [15]:
anti_diagonal = grid[[0,1,2,3,4],[4,3,2,1,0]]
print(anti_diagonal)

[ 5  9 13 17 21]


## Extract the outer border (excluding center elements)

In [40]:
print(grid)
border = np.concatenate((
    grid[0, :],           # top row
    grid[1:4, 4],         # right column (excluding top & bottom)
    grid[4, ::-1],        # bottom row reversed
    grid[3:0:-1, 0]       # left column upward (excluding top & bottom)
))
print(border)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  2  3  4  5 10 15 20 25 24 23 22 21 16 11  6]


## 🔹 Task 1: Flip the Matrix Horizontally (Left ↔ Right)

In [41]:
flipped_lr = np.fliplr(grid)
print('Horizontally Flipped:\n',flipped_lr)

Horizontally Flipped:
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


## 🔹 Task 2: Flip the Matrix Vertically (Top ↕ Bottom)

In [42]:
flipped_ud = np.flipud(grid)
print(flipped_ud)

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


## 🔹 Task 3: Rotate the Matrix 180°

## Method 1: Use np.rot90(grid, 2)

In [43]:
rotated = np.rot90(grid)
print(rotated)

[[ 5 10 15 20 25]
 [ 4  9 14 19 24]
 [ 3  8 13 18 23]
 [ 2  7 12 17 22]
 [ 1  6 11 16 21]]


## Method 2 (Manual flip both ways):

In [44]:
rotated_manual = np.flipud(np.fliplr(grid))
print(rotated_manual)

[[25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Replace all even numbers in the grid with 0

In [45]:
grid_even = grid % 2 == 0
grid[grid_even] = 0
print(grid)

[[ 1  0  3  0  5]
 [ 0  7  0  9  0]
 [11  0 13  0 15]
 [ 0 17  0 19  0]
 [21  0 23  0 25]]


## Replace all odd numbers with 1

In [48]:
grid_odd = grid % 2 !=0
grid[(grid_odd)] = 1
print(grid)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [49]:
grid = np.arange(1, 26).reshape(5,5)
print('Initial Grid:\n',grid)

Initial Grid:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


## Create a mask of values greater than 10

In [50]:
mask = grid[grid >10]
print(mask)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


## Replace all numbers greater than 15 with -1

In [52]:
grid[grid>15] = -1
print(grid)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [53]:
grid = np.arange(1,26).reshape(5,5)
print(grid)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


## Extract all values divisible by 3

In [55]:
print(grid[grid % 3 ==0])

[ 3  6  9 12 15 18 21 24]


## 1. Flatten the grid to a 1D array

In [57]:
print(grid.flatten())
print(grid.flatten().shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
(25,)


## 2. Reshape into a 1-row matrix (1×25)

In [59]:
print(grid.reshape(1,25))
print(grid.reshape(1,25).shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25]]
(1, 25)


## 3. Reshape into a column matrix (25×1)

In [60]:
print(grid.reshape(25,1))
print(grid.reshape(25,1).shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]]
(25, 1)


## 4. Reshape into a 3×8 matrix

In [71]:
flat = grid.flatten()
padded = np.pad(flat , (0,1) , mode = 'constant' , constant_values = 0)
padded_24 = padded[:24]
reshaped = padded_24.reshape(3,8)
print(reshaped)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
