# ✅ Step 1: Create the Sales Data

## We’ll create a 6 × 4 matrix — 6 products, 4 weeks.

In [3]:
import numpy as np

#making results reproducible
np.random.seed(1) #this makes the random data to be fixed 

sales = np.random.randint(100, 500, size = (6,4))
print('Sales Data (Products x Weeks):\n', sales)
print('Shape: ',sales.shape)
print('Total Number of Sales records: ', sales.size)

Sales Data (Products x Weeks):
 [[137 335 496 172]
 [355 493 303 233]
 [435 244 229 171]
 [337 490 381 278]
 [376 354 457 495]
 [352 256 498 150]]
Shape:  (6, 4)
Total Number of Sales records:  24


# ✅ Step 2: Calculate Weekly and Product-wise Totals & Averages
## 🎯 Goals:
## 1.Find how each product performed across 4 weeks (row-wise)
## 2.Find how each week performed across products (column-wise)
## 3.Calculate both totals and averages

In [4]:
#1.
product_totals = np.sum(sales, axis = 1)
product_mean = np.mean(sales, axis = 1)
#2.
week_total = np.sum(sales, axis = 0)
week_mean = np.mean(sales, axis = 0)
week_mean_rounded = np.round(week_mean, 2)
print('The Total performance by each product is : ', product_totals)
print('The Average performance by each product is : ', product_mean)
print('The Total performance per week is : ', week_total)
print('The Average performance per week is : ', week_mean_rounded)

The Total performance by each product is :  [1140 1384 1079 1486 1682 1256]
The Average performance by each product is :  [285.   346.   269.75 371.5  420.5  314.  ]
The Total performance per week is :  [1992 2172 2364 1499]
The Average performance per week is :  [332.   362.   394.   249.83]


# ✅ Step 3: Find Best and Worst Performing Product & Week
## 🎯 Goals:
## 1.Identify the product with the highest and lowest total sales
## 2.Identify the week with the highest and lowest total sales
## 3.This is where we use:
## np.argmax() → gives index of max value
## np.argmin() → gives index of min value

In [16]:
#1.
product_total = np.sum(sales, axis = 1)
best_product_index = np.argmax(product_total)
worst_product_index = np.argmin(product_total)
#2.
week_total = np.sum(sales, axis = 0)
best_week_index = np.argmax(week_total)
worst_week_index = np.argmin(week_total)
print('Data'.center(35,'#'))
print('Product Data: ',product_total)
print('Week Data: ',week_total)
print('Products Performance'.center(40,'*'))
print('Best Product in performance: ',best_product_index + 1)
print('Worst Product in performance: ',worst_product_index  + 1)
print('Weeks Performance'.center(40,'*'))
print('Best Performing week: ',best_week_index + 1)
print('Worst Performing week: ',worst_week_index + 1)


################Data###############
Product Data:  [1140 1384 1079 1486 1682 1256]
Week Data:  [1992 2172 2364 1499]
**********Products Performance**********
Best Product in performance:  5
Worst Product in performance:  3
***********Weeks Performance************
Best Performing week:  3
Worst Performing week:  4


# ✅ Step 4: Add Extra Information Using Stacking (hstack, vstack)
## This is super useful when:
## You want to add a bonus column to each product’s data (like festival sales)
## Or add a total row showing combined weekly sales across all products

# 🔹 Scenario 1: Add a Bonus Column to Each Product
## Let’s say there was a Diwali bonus sale added to each product. We'll simulate that with a new column of 6 values (one per product).

In [23]:
#first create an extra column as a diwali bonus to add it to the main array
np.random.seed(1)
diwali_sales = np.random.randint(50, 151, size = (6,1))
print("Diwali Sales Data:\n",diwali_sales)
updated_sales = np.hstack((sales, diwali_sales))
print('Sales + Diwali Sales: \n',updated_sales)

Diwali Sales Data:
 [[ 87]
 [ 62]
 [122]
 [ 59]
 [125]
 [ 55]]
Sales + Diwali Sales: 
 [[137 335 496 172  87]
 [355 493 303 233  62]
 [435 244 229 171 122]
 [337 490 381 278  59]
 [376 354 457 495 125]
 [352 256 498 150  55]]


# 🔹 Scenario 2: Add a Total Row at the Bottom
## Want to see total sales per week across all products?

In [26]:
week_totals = np.sum(sales, axis = 0).reshape(1, -1)
sales_with_totals = np.vstack((sales, week_totals))
product_totals = np.sum(sales_with_totals, axis =1).reshape(-1 , 1)
updated_totals = np.hstack((sales_with_totals, product_totals))
print('Sales with total week row & product row:\n', updated_totals)

Sales with total week row & product row:
 [[ 137  335  496  172 1140]
 [ 355  493  303  233 1384]
 [ 435  244  229  171 1079]
 [ 337  490  381  278 1486]
 [ 376  354  457  495 1682]
 [ 352  256  498  150 1256]
 [1992 2172 2364 1499 8027]]


# ✅ Step 5: Reshape and Flatten for ML-Style Input
## 🎯 Goal:
## Prepare your data in different shapes suitable for:
## Feeding into machine learning models (like scikit-learn)
## Analysis pipelines or exporting
## Flattening 2D data into 1D features



🔹 1. Flatten Entire Dataset into a 1D Vector

In [27]:
flat = sales.flatten()
print("Flattened array:\n", flat)
print("Shape:", flat.shape)  # (24,)

Flattened array:
 [137 335 496 172 355 493 303 233 435 244 229 171 337 490 381 278 376 354
 457 495 352 256 498 150]
Shape: (24,)


🔹 2. Convert to a Single Row (1 × 24)

In [28]:
row_input = sales.reshape(1, -1)
print("Row view:\n", row_input)
print("Shape:", row_input.shape)  # (1, 24)

Row view:
 [[137 335 496 172 355 493 303 233 435 244 229 171 337 490 381 278 376 354
  457 495 352 256 498 150]]
Shape: (1, 24)


🔹 3. Convert to a Single Column (24 × 1)

In [29]:
col_input = sales.reshape(-1, 1)
print("Column view:\n", col_input)
print("Shape:", col_input.shape)  # (24, 1)

Column view:
 [[137]
 [335]
 [496]
 [172]
 [355]
 [493]
 [303]
 [233]
 [435]
 [244]
 [229]
 [171]
 [337]
 [490]
 [381]
 [278]
 [376]
 [354]
 [457]
 [495]
 [352]
 [256]
 [498]
 [150]]
Shape: (24, 1)
