✅ Step 1: Generate the Marks Data
We will create a 5x4 NumPy array → 5 students × 4 subjects

In [2]:
import numpy as np
np.random.seed(0) # makes the fixed random values for every time and each random value changes on change of seed value 
marks = np.random.randint(40,100, size = (5,4)) #creates random values between 40 and 100
print('Marks of Students:\n',marks)

Marks of Students:
 [[84 87 93 40]
 [43 99 43 79]
 [49 59 61 90]
 [76 63 46 64]
 [64 52 98 41]]


✅ Step 2: Average marks of each students

In [29]:
student_avg = np.mean(marks,axis = 1) #row - wise average
print('Average Marks:\n',student_avg)

Average Marks:
 [76.   66.   64.75 62.25 63.75]


In [24]:
# Get topper student indices for each subject
topper_indices = np.argmax(marks , axis = 0)
print('Topper Indices per subject:\n',topper_indices+1)

Topper Indices per subject:
 [1 2 5 3]


✅ Step 3: Get the maximum marks from the array using fancy indexing

In [30]:
toppers = marks[topper_indices, np.arange(marks.shape[1])]
print('Topper marks in each subject:\n',toppers)

Topper marks in each subject:
 [84 99 98 90]


✅ Step 4: Find Students Who Scored Above 80 in All Subjects

In [38]:
#check which student has scored above 80 in all subjects
above_80_all = np.all(marks>80, axis = 1) #boolean mask for every student 
print(above_80_all)
high_achievers = marks[above_80_all] 
print(high_achievers)

[False False False False False]
[]


✅ Step 5: Reshaping the Data for New Views
🎯 Goal:
Change how the data is represented — like flattening it into a row or column — which is super useful in:

🧠 Machine learning input preparation

📊 Visualization tools

🔁 Matrix operations

🔄 Reshape to a Single Row (1 × 20)

In [42]:
row_view = marks.reshape(1, -1)
print("Reshaped as 1 row:\n", row_view)
print("Shape:", row_view.shape)

Reshaped as 1 row:
 [[84 87 93 40 43 99 43 79 49 59 61 90 76 63 46 64 64 52 98 41]]
Shape: (1, 20)


⬇️ Reshape to a Column Vector (20 × 1)

In [43]:
col_view = marks.reshape(-1, 1)
print("Reshaped as column vector:\n", col_view)
print("Shape:", col_view.shape)

Reshaped as column vector:
 [[84]
 [87]
 [93]
 [40]
 [43]
 [99]
 [43]
 [79]
 [49]
 [59]
 [61]
 [90]
 [76]
 [63]
 [46]
 [64]
 [64]
 [52]
 [98]
 [41]]
Shape: (20, 1)


🔄 Flatten the Matrix

In [41]:
flat = marks.flatten()
print("Flattened Array:\n", flat)
print("Shape:", flat.shape)

Flattened Array:
 [84 87 93 40 43 99 43 79 49 59 61 90 76 63 46 64 64 52 98 41]
Shape: (20,)
